#login page
makeAppointment = //a[@id='btn-make-appointment']
loginLabel  = //h2[normalize-space()='Login']
pleaselogintoMakeAppointment = //p[@class='lead']
username = //input[@value='John Doe']
password = //input[@value='ThisIsNotAPassword']
userNameField = //input[@id='txt-username']
passwordField = //input[@id='txt-password']
loginButton = //button[@id='btn-login']

#Appointment file
makeAppointmentHeader = //h2[normalize-space()='Make Appointment']
facilitydropdown = //select[@id='combo_facility']
readmissionCheckbox = //*[@id=\"chk_hospotal_readmission\"]
healthcareProgram = //*[@id=\"radio_program_medicaid\"]
visitdate = //*[@id=\"txt_visit_date\"]
comment = //*[@id=\"txt_comment\"]
bookAppointmentButton = //*[@id=\"btn-book-appointment\"]

# Summary
AppointmentConfirmation = //*[@id=\"summary\"]/div/div/div[1]/h2
goToHomePageButton = //*[@id=\"summary\"]/div/div/div[7]/p/a